# DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate SQL Log
logging.level.org.hibernate.SQL=info
logging.level.org.hibernate.orm.jdbc.bind=off

# JWT Secret
jwt.secret=${JWT_SECRET}

# JWT 만료 시간
jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION}
jwt.refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION}

# CORS
app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN}

# Cookie
app.cookie.secure=true
app.cookie.same-site=Lax

# AWS
app.aws.region=ap-northeast-2

# S3 Image Storage
app.aws.s3.bucket=${APP_AWS_S3_BUCKET}

# referenceId가 null이고 updatedAt이 24시간보다 오래된 이미지만 삭제
app.image.orphan-retention-hours=24

# 고아 이미지 정리 : 매일 새벽 3시
app.image.cleanup.cron=0 0 3 * * *

# 조회수 스케줄러 동작 주기
app.view-count.flush-delay-ms=5000

