apiVersion: v1
kind: Secret
metadata:
  name: community-backend-secret
  namespace: community-prod-backend
  labels:
    app: community
    tier: backend
    env: prod
type: Opaque
stringData:
  DB_USERNAME: community_app
  DB_PASSWORD: bmh9764imes
  JWT_SECRET: 9cSuPAkP60FBnIXbrvd49BHFnjTlx8kGyM4VYrvMG3iEYa2zhoGCKJQbI99C