apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd

spec:
  description: Infrastructure add-ons managed by Argo CD

  # 이 Project의 Application이 사용할 수 있는 저장소
  sourceRepos:
    # 프로젝트에서 관리하는 Helm Values 파일
    - https://github.com/LimChanHyeok/4-max-community-BE.git

    # AWS EBS CSI Driver 공식 Helm 저장소
    - https://kubernetes-sigs.github.io/aws-ebs-csi-driver

    # kube-prometheus-stack 공식 Helm 저장소
    - https://prometheus-community.github.io/helm-charts

    # loke 공식 저장소
    - https://grafana-community.github.io/helm-charts

    # Alloy 공식 저장소
    - https://grafana.github.io/helm-charts

  # 이 Project가 배포할 수 있는 Namespace
  destinations:
    # AWS EBS CSI Driver 등 클러스터 Add-on
    - server: https://kubernetes.default.svc
      namespace: kube-system

    # Prometheus, Grafana, kube-state-metrics 등 모니터링 구성요소
    - server: https://kubernetes.default.svc
      namespace: monitoring

  # Namespace에 속하는 리소스 허용
  # 다양한 종류의 리소스를 생성하므로 인프라 Project 안에서는
  # 모든 Namespaced 리소스를 허용한다.
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  # Namespace에 속하지 않는 클러스터 범위 리소스 허용
  # Chart 버전 변경 시 생성 리소스 종류가 달라질 수 있으므로
  # 인프라 Add-on 전용 Project에서는 모든 클러스터 리소스를 허용한다.
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"